// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Data;

#nullable disable

namespace Portfolio.Data.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    [Migration("20260823103008_GenericFileStorage")]
    partial class GenericFileStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Core.Models.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CompressedSize")
                        .HasColumnType("bigint");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<long?>("TimeUploaded")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Portfolio.Core.Models.LinkModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("CustomColour")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectElementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectElementParameterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ParameterValue1")
                        .HasColumnType("text");

                    b.Property<string>("ParameterValue2")
                        .HasColumnType("text");

                    b.Property<string>("ParameterValue3")
                        .HasColumnType("text");

                    b.Property<int>("ProjectElementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectElementId");

                    b.ToTable("ElementsParameters");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("genre")
                        .HasColumnType("text");

                    b.Property<string>("icon")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("projectType")
                        .HasColumnType("integer");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectTagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ReleaseDownloadModel", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReleaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<long>("DownloadSize")
                        .HasColumnType("bigint");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntryPoint")
                        .HasColumnType("text");

                    b.Property<string>("ReleaseEngineManifest")
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "ReleaseId", "Platform");

                    b.ToTable("ReleaseDownloads");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ReleaseModel", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReleaseId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatchNotes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VersionName")
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "ReleaseId");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("Portfolio.Core.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customColour")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectElementModel", b =>
                {
                    b.HasOne("Portfolio.Core.Models.ProjectModel", "Project")
                        .WithMany("Elements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectElementParameterModel", b =>
                {
                    b.HasOne("Portfolio.Core.Models.ProjectElementModel", "ProjectElement")
                        .WithMany("Parameters")
                        .HasForeignKey("ProjectElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectElement");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectTagModel", b =>
                {
                    b.HasOne("Portfolio.Core.Models.ProjectModel", "project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Core.Models.TagModel", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("project");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ReleaseDownloadModel", b =>
                {
                    b.HasOne("Portfolio.Core.Models.ReleaseModel", "MetaData")
                        .WithMany("Downloads")
                        .HasForeignKey("ProjectId", "ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaData");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ReleaseModel", b =>
                {
                    b.HasOne("Portfolio.Core.Models.ProjectModel", "Project")
                        .WithMany("Releases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectElementModel", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ProjectModel", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Releases");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Portfolio.Core.Models.ReleaseModel", b =>
                {
                    b.Navigation("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
